[package]
name = "movie_collection_rust"
version = "0.3.24"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
movie_collection_lib = {path = "movie_collection_lib"}
movie_collection_http = {path = "movie_collection_http"}
rayon = "1.2"
clap = "2.33"
failure = "0.1"
log = "0.4"
env_logger = "0.7"
subprocess = "0.1"
actix = "0.8.3"
actix-rt = "0.2"

[workspace]
members = [
    "movie_collection_lib", "movie_collection_http"
]

[[bin]]
name = "make-list"
path = "src/make_list.rs"
doc = false

[[bin]]
name = "remcom"
path = "src/remcom.rs"
doc = false

[[bin]]
name = "transcode-avi"
path = "src/transcode_avi.rs"
doc = false

[[bin]]
name = "run-encoding"
path = "src/run_encoding.rs"
doc = false

[[bin]]
name = "parse-imdb"
path = "src/parse_imdb.rs"
doc = false

[[bin]]
name = "make-collection"
path = "src/make_collection.rs"
doc = false

[[bin]]
name = "make-queue"
path = "src/make_queue.rs"
doc = false

[[bin]]
name = "movie-queue-http"
path = "src/movie_queue_http.rs"
doc = false

[[bin]]
name = "find-new-episodes"
path = "src/find_new_episodes.rs"
doc = false

[[bin]]
name = "trakt-app"
path = "src/trakt_app.rs"
doc = false
