[package]
name = "movie_collection_rust"
version = "0.1.20"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
postgres = {version = "0.15", features = ["with-chrono"]}
subprocess = "0.1"
r2d2 = "*"
r2d2_postgres = "*"
failure = "*"
rayon = "1.0"
clap = "*"
dotenv = "*"
amqp = {version="*", default_features=false}
select = "*"
reqwest = "*"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.6"
actix = "*"
actix-web = "*"
futures = "*"
jsonwebtoken = "5.0"

[lib]
name = "movie_collection_rust"
path = "src/lib.rs"

[[bin]]
name = "make-list"
path = "src/make_list.rs"
doc = false

[[bin]]
name = "remcom"
path = "src/remcom.rs"
doc = false

[[bin]]
name = "transcode-avi"
path = "src/transcode_avi.rs"
doc = false

[[bin]]
name = "run-encoding"
path = "src/run_encoding.rs"
doc = false

[[bin]]
name = "parse-imdb"
path = "src/parse_imdb.rs"
doc = false

[[bin]]
name = "make-collection"
path = "src/make_collection.rs"
doc = false

[[bin]]
name = "make-queue"
path = "src/make_queue.rs"
doc = false

[[bin]]
name = "movie-queue-http"
path = "src/movie_queue_http.rs"
doc = false

[[bin]]
name = "find-new-episodes"
path = "src/find_new_episodes.rs"
doc = false

[[bin]]
name = "trakt-app"
path = "src/trakt_app.rs"
doc = false
