[package]
name = "movie_collection_rust"
version = "0.1.0"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
postgres = "0.15"
subprocess = "0.1"
r2d2 = "*"
r2d2_postgres = "*"
failure = "*"
rayon = "1.0"

[lib]
name = "movie_collection_rust"
path = "src/lib.rs"

[[bin]]
name = "make_list"
path = "src/make_list.rs"
doc = false

