[package]
name = "movie_collection_lib"
version = "0.4.0"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
postgres = {version = "0.17", features = ["with-chrono-0_4"]}
subprocess = "0.1"
r2d2 = "0.8"
r2d2_postgres = "0.16"
failure = "0.1"
rayon = "1.3"
clap = "2.33"
dotenv = "0.15"
amqp = {version="0.1", default_features=false}
select = "0.4"
reqwest = "0.9"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.7"
futures = "0.3"
log = "0.4"
env_logger = "0.7"
simple_logger = "1.3"
actix = "0.9"
cpython = "0.3"
retry = "0.5"
