[package]
name = "movie_collection_lib"
version = "0.5.2"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
tokio-postgres = {version="0.5", features=["with-chrono-0_4"]}
subprocess = "0.2"
deadpool = "0.5"
deadpool-postgres = "0.5"
rayon = "1.3"
clap = "2.33"
dotenv = "0.15"
amqp = {version="0.1", default_features=false}
select = "0.4"
reqwest = {version="0.10", features=["cookies", "json"]}
chrono = { version = "0.4", features = ["serde"] }
rand = "0.7"
futures = "0.3"
log = "0.4"
env_logger = "0.7"
simple_logger = "1.5"
actix = "0.9"
cpython = "0.4"
retry = "1.0"
postgres_query = "0.3"
bytes = "0.5"
anyhow = "1.0"
thiserror = "1.0"
dirs = "2.0"
tokio = {version="0.2", features=["full"]}
async-trait = "0.1"
futures-retry = "0.4"
derive_more = "0.99"
structopt = "0.3"