[package]
name = "movie_collection_http"
version = "0.5.35"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
movie_collection_lib = {path = "../movie_collection_lib"}
actix = "0.9"
actix-web = "2.0"
actix-rt = "1.1"
actix-identity = "0.2"
futures = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.4"
subprocess = "0.2"
tokio = {version="0.2", features=["time"]}
parking_lot = "0.11"
lazy_static = "1.4"
anyhow = "1.0"
thiserror = "1.0"
actix-threadpool = "0.3"
rust_auth_server = { git = "https://github.com/ddboline/rust-auth-server.git", tag="0.5.15" }
async-trait = "0.1"
log = "0.4"
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.1.3", features=["postgres_types"] }
