[package]
name = "movie_collection_http"
version = "0.3.18"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
movie_collection_lib = {path = "../movie_collection_lib"}
actix = "0.8.3"
actix-web = "1.0.5"
actix-rt = "0.2"
actix-identity = "0.1"
failure = "0.1"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.4"
subprocess = "0.1"
jsonwebtoken = "6.0"
tokio-timer = "0.2"
parking_lot = "0.9"
lazy_static = "1.4"
