[package]
name = "movie_collection_http"
version = "0.4.0"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
movie_collection_lib = {path = "../movie_collection_lib"}
actix = "0.9"
actix-web = "2.0"
actix-rt = "1.0"
actix-identity = "0.2"
failure = "0.1"
futures = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.4"
subprocess = "0.1"
jsonwebtoken = "7.0.0-alpha.2"
tokio = {version="0.2", features=["time"]}
parking_lot = "0.10"
lazy_static = "1.4"
